Updates on docs

diff --git a/.husky/post-commit b/.husky/post-commit
--- a/.husky/post-commit
+++ b/.husky/post-commit
@@ -7,5 +7,11 @@ if [ -f "$FILE_NAME" ]; then
   # shellcheck source=./_/husky.sh
   . "$FILE_NAME"
 
+  command -v git-lfs >/dev/null 2>&1 || {
+    echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"
+    exit 2
+  }
+  git lfs post-commit "$@"
+
   npm run validate:commit
 fi
